version: 2
jobs:
  build:

    working_directory: ~/Bemore_Exam

    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/mysql:latest
        command: [--default-authentication-plugin=mysql_native_password]
          environment:
            MYSQL_DATABASE: db_users


    steps:

      - checkout

      - restore_cache:
          key: Bemore_Exam-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: Bemore_Exam-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/Bemore-0.0.1-SNAPSHOT.jar
