version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: root
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_PASSWORD:
            - image: mysql:latest
              command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
              environment:
                MYSQL_USER: root
                MYSQL_ALLOW_EMPTY_PASSWORD: true


    working_directory: ~/Bemore_Exam

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      # git pull
      - checkout


      # Download and cache dependencies
      - restore_cache:
          keys:
            - Bemore_Exam-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: Bemore_Exam-{{ checksum "pom.xml" }}

      # package into a jar
      - run: mvn integration-test cobertura:cobertura

      # build and push docker image to docker hub

      # store raw contents of src code
      - store_test_results:
          path: target/surefire-reports


